### ISSUE TITLE
Port to chrome extension

### ISSUE THREAD

**Issue by corsair992** [MarcinOrlowski/StackUnderflow#1]
Could this be ported as a chrome extension? And preferably be added to the Chrome Web Store subsequently? You might also consider posting this on [Stack Apps](http://stackapps.com) for more publicity.

**Comment by MarcinOrlowski** [comment]
Thanks, for referencing Stack Apps - I just [posted announcement there](https://stackapps.com/questions/6534/stackunderflow-greasemonkey-tampermonkey-helper-script-for-stackoverflow-users) 

As for making it chrome extension - I will look into it. Thanks

**Comment by MarcinOrlowski** [comment]
as for Chrome extension - unless there's easy way of doing so, It's most likely won't happen. Please let me know if there's such way so I will reopen this ticket.
