### ISSUE TITLE
How can I fully disable the "user blacklisting, favorites" feature?

### ISSUE THREAD

**Issue by K-Guan** [MarcinOrlowski/StackUnderflow#4]
Hmm...I don't need that feature, but I think other features are very good.

However, I'm trying to disable it. I tried set the `cfg_enablePostedByFavouriteUserWarning` and `cfg_enablePostedByBlacklistedUserWarning` false, but I also don't want the blacklist/favorite buttons. 

How can I do it?

**Comment by MarcinOrlowski** [comment]
You cannot in v0.5. But that's easy fix, so I will add it shortly.
